import { spawn } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fleetHome } from '@fleetadlc/github';
import type { InstallConfig } from '../install.js';
import { prompt, ui } from '../ui.js';
import { checkBucket, pullSettings } from './cloud-bucket.js';
import { explainTerraformFailure, findLeftovers, leftoversMessage, ownedAddresses, type GcloudResult } from './cloud-leftovers.js';

const PROVIDERS = ['gcp'] as const;
type Provider = (typeof PROVIDERS)[number];

/**
 * Where an install's Terraform state lives, and next to it the install's own
 * settings.
 *
 * The module is OpenADLC's and ships in this repository; the values that make it
 * one install — the project, the domain, the organization, who may open the
 * console, the webhook secret — are not, and must not be. They used to exist
 * only as `$FLEETADLC_HOME/cloud.tfvars.json` on whichever machine ran `configure`,
 * with the state beside the module in the checkout: the next operator, or the
 * same one on a new laptop, had neither. Both now live in a bucket in the
 * install's own project, so any machine with access can `fleetadlc cloud pull` and
 * carry on.
 */
export interface CloudBackend {
  bucket: string;
  prefix: string;
}

export interface CloudConfig {
  provider: Provider;
  projectId: string;
  region: string;
  zone: string;
  organization: string;
  githubClientId: string;
  humans: string[];
  consoleDomain: string;
  bridgeImage: string;
  consoleImage: string;
  /** The host's own image, and the image each bot's container runs. */
  hostdImage: string;
  botImage: string;
  consoleMembers: string[];
  /** The console's first admins, written as `admin_emails`; empty, and the `user:` console members are. */
  adminEmails: string[];
  operators: string[];
  /** Generated by the first `configure` and kept in cloud.tfvars.json after; GitHub signs deliveries with it. */
  webhookSecret: string;
  /** owner/name of a repository whose workflow may roll out new images; empty for none. */
  deployerRepository?: string;
  /**
   * The deployer repository's numeric id and its owner's, which the identity
   * provider admits it by, and the one workflow file in it that may deploy.
   * Written only with a deployer repository.
   */
  deployerRepositoryId?: string;
  deployerRepositoryOwnerId?: string;
  deployerWorkflow?: string;
  /** Cloud Monitoring channels the alerts go to; none, and an alert notifies nobody. */
  notificationChannels?: string[];
}

const TFVARS = 'cloud.tfvars.json';

/** The module's default for `deployer_workflow`. */
export const DEFAULT_DEPLOYER_WORKFLOW = '.github/workflows/deploy.yml';

/**
 * Every resource the module makes is named from this. Settings written before
 * the rename to FleetADLC carry no `name_prefix`, and their resources were made
 * under the module's old default, `fleet` — applying them with the new default
 * would replace the network, the database and the host rather than update them.
 */
export const NAME_PREFIX = 'fleetadlc';
export const LEGACY_NAME_PREFIX = 'fleet';

/** The settings, with the name the install's resources already have pinned in. */
export function pinNamePrefix(vars: Record<string, unknown>): { vars: Record<string, unknown>; pinned: boolean } {
  if (typeof vars.name_prefix === 'string' && vars.name_prefix.length > 0) return { vars, pinned: false };
  return { vars: { ...vars, name_prefix: LEGACY_NAME_PREFIX }, pinned: true };
}
const BACKEND = 'cloud.backend.json';

function tfVarsPath(): string {
  return join(fleetHome(), TFVARS);
}

function backendPath(): string {
  return join(fleetHome(), BACKEND);
}

function moduleDir(config: InstallConfig, provider: Provider): string {
  return join(config.repoRoot, 'infra', provider);
}

/** The module's inputs, by the names its variables.tf declares. */
export function tfVars(cloud: CloudConfig, hostdPort: number): Record<string, unknown> {
  return {
    project_id: cloud.projectId,
    region: cloud.region,
    zone: cloud.zone,
    github_organization: cloud.organization,
    github_app_client_id: cloud.githubClientId,
    humans: cloud.humans,
    console_domain: cloud.consoleDomain,
    bridge_image: cloud.bridgeImage,
    console_image: cloud.consoleImage,
    // Both are required by the module and neither was written here, so
    // `terraform apply` stopped to ask for them — and `bot_image` had no
    // asking to do, because nothing provisioned a bot image at all.
    hostd_image: cloud.hostdImage,
    bot_image: cloud.botImage,
    console_members: cloud.consoleMembers,
    admin_emails: cloud.adminEmails,
    operators: cloud.operators,
    webhook_secret: cloud.webhookSecret,
    hostd_port: hostdPort,
    name_prefix: NAME_PREFIX,
    ...(cloud.deployerRepository
      ? {
          deployer_repository: cloud.deployerRepository,
          deployer_repository_id: cloud.deployerRepositoryId ?? '',
          deployer_repository_owner_id: cloud.deployerRepositoryOwnerId ?? '',
          deployer_workflow: cloud.deployerWorkflow || DEFAULT_DEPLOYER_WORKFLOW,
        }
      : {}),
    ...(cloud.notificationChannels?.length ? { notification_channels: cloud.notificationChannels } : {}),
  };
}

/**
 * The settings `configure` writes, over the ones the install already has.
 *
 * `configure` once built them from its answers alone, with a new webhook
 * secret each run: run again on a live install, to set the deployer, it
 * rotated the secret at the next apply so GitHub's deliveries failed
 * verification, dropped settings added by hand such as `admin_emails`, and on
 * an install from before the rename reset `name_prefix` to `fleetadlc`, so
 * plan looked at an empty state. Now the secret is made only when there is
 * none, everything not asked about carries over, and the prefix is the one the
 * install's resources already have.
 */
export function configuredVars(
  existing: Record<string, unknown> | undefined,
  answers: Omit<CloudConfig, 'webhookSecret'>,
  hostdPort: number,
  secret: () => string,
): Record<string, unknown> {
  const kept = typeof existing?.webhook_secret === 'string' && existing.webhook_secret ? existing.webhook_secret : secret();
  const vars = tfVars({ ...answers, webhookSecret: kept }, hostdPort);
  if (!existing) return vars;
  // tfVars always writes the new prefix, so the old one is put back after the merge.
  return pinNamePrefix({ ...existing, ...vars, name_prefix: existing.name_prefix }).vars;
}

/**
 * The console members that name a person, as bare addresses: the default for
 * the first admins. A `group:` or `domain:` member names nobody the bridge can
 * make admin, so an install that lets people in only that way had no admin.
 */
export function consoleUsers(members: string[]): string[] {
  return members.filter((member) => member.startsWith('user:')).map((member) => member.slice('user:'.length)).filter(Boolean);
}

/**
 * What `configure` says when the first admins name nobody. It still writes
 * the settings: the install can be deployed, and the bridge refuses every
 * visitor with "no admin is configured" until this is fixed.
 */
export function noAdminWarning(adminEmails: string[], settingsPath: string): string | null {
  if (adminEmails.length > 0) return null;
  return `the console will have no admin: nobody is named, so every visitor is refused. Add "admin_emails": ["you@example.com"] to ${settingsPath} and run: fleetadlc cloud apply`;
}

/** A setting from `existing` as a prompt's default: a list joined with commas. */
/**
 * What `configure` offers before an install has settings of its own, from the
 * environment: infra/gcp/install.sh has already asked gcloud for the project,
 * the region and who is signed in, and would otherwise have the person type
 * all three again. An install's own settings come first, whatever these say.
 */
export function configureDefaults(env: Readonly<Record<string, string | undefined>>): {
  projectId?: string;
  region?: string;
  consoleMembers?: string;
} {
  const value = (name: string): string | undefined => env[name]?.trim() || undefined;
  return {
    projectId: value('FLEETADLC_CLOUD_PROJECT'),
    region: value('FLEETADLC_CLOUD_REGION'),
    consoleMembers: value('FLEETADLC_CLOUD_CONSOLE_MEMBERS'),
  };
}

function shown(existing: Record<string, unknown> | undefined, key: string): string | undefined {
  const value = existing?.[key];
  if (typeof value === 'string' && value) return value;
  if (Array.isArray(value) && value.length > 0) return value.filter((entry) => typeof entry === 'string').join(',');
  return undefined;
}

/**
 * GitHub's own spelling of a repository, for the deployer.
 *
 * The deployer's identity condition (`infra/gcp/deployer.tf`) compares the
 * token's `repository` claim, which GitHub fills with the canonical name, as a
 * string: `exampleco/deploys` typed for `ExampleCo/Deploys` refused every
 * deploy at token exchange, with nothing saying case was why. GitHub's lookup
 * ignores case, so it answers with the right spelling. A repository it will
 * not show without a sign-in, a private one, is kept as typed.
 *
 * The same answer carries the repository's numeric id and its owner's, which
 * the provider admits it by: a name is freed by a rename or a transfer and
 * can be taken by someone else, an id cannot.
 */
export async function canonicalRepository(
  typed: string,
  lookup: (url: string) => Promise<{ ok: boolean; json(): Promise<unknown> }> = (url) =>
    fetch(url, { headers: { accept: 'application/vnd.github+json' } }),
): Promise<{ name: string; checked: boolean; id?: string; ownerId?: string }> {
  if (!/^[A-Za-z0-9-]+\/[A-Za-z0-9._-]+$/.test(typed)) return { name: typed, checked: false };
  try {
    const answer = await lookup(`https://api.github.com/repos/${typed}`);
    if (!answer.ok) return { name: typed, checked: false };
    const repo = (await answer.json()) as { full_name?: unknown; id?: unknown; owner?: { id?: unknown } | null };
    if (typeof repo.full_name !== 'string' || repo.full_name.toLowerCase() !== typed.toLowerCase()) return { name: typed, checked: false };
    const id = numericId(repo.id);
    const ownerId = numericId(repo.owner?.id);
    return { name: repo.full_name, checked: true, ...(id && ownerId ? { id, ownerId } : {}) };
  } catch {
    return { name: typed, checked: false };
  }
}

/** A GitHub id as the token's claims carry it: decimal digits, as a string. */
function numericId(value: unknown): string | undefined {
  if (typeof value === 'number' && Number.isSafeInteger(value) && value > 0) return String(value);
  if (typeof value === 'string' && /^[0-9]+$/.test(value)) return value;
  return undefined;
}

/** `terraform init`'s arguments for the install's bucket. */
export function backendArgs(backend: CloudBackend): string[] {
  return ['-reconfigure', `-backend-config=bucket=${backend.bucket}`, `-backend-config=prefix=${backend.prefix}`];
}

/** Where the settings sit in the bucket: beside the state, under the same prefix. */
export function remoteTfVars(backend: CloudBackend): string {
  return `gs://${backend.bucket}/${backend.prefix}/${TFVARS}`;
}

/**
 * What is left by hand after an apply. The webhook line once sent the
 * operator to `bridge_url`, the internal Cloud Run address GitHub can never
 * reach, and to a webhook on the organization, when the bridge listens to the
 * app's, whose stored secret wins over the module's. And the rest once said
 * to run `fleetadlc auth login`, `doctor` and `restore` on the host, which
 * runs Container-Optimized OS and has no fleetadlc; from a laptop they wrote
 * to the wrong secret store and probed the wrong install. The console does
 * all three.
 */
export function postApplySteps(settingsPath: string): string[] {
  return [
    'point DNS for the console domain at console_ip (fleetadlc cloud output)',
    'connect the bots’ GitHub accounts in the console’s walkthrough, at its GitHub accounts step (GitHub needs a person at a browser), or restore a backup in its first step, taking over the sign-ins',
    `an app created from the console already delivers here, with the secret it stored: leave its webhook alone. After a restore, or for an app made by hand, use the console’s webhook step, which sets one secret on both sides. Only for an app made by hand on a fresh install, point the GitHub App’s webhook (on the app’s settings page) at webhook_url (fleetadlc cloud output), with the webhook_secret in ${settingsPath} as its secret. The console’s webhook card shows whether a delivery arrived`,
    'check the install on the console’s health cards and its walkthrough',
  ];
}

/**
 * Asks until there is an answer. `prompt` shows a default in parentheses, and
 * these questions put an example there: Enter took what looked like
 * `fleetadlc.example.com` and wrote an empty console domain, which was then
 * pushed to the bucket.
 */
export async function askRequired(
  ask: (question: string, fallback?: string) => Promise<string>,
  question: string,
  fallback?: string,
): Promise<string> {
  for (;;) {
    const answer = (await ask(question, fallback ?? '')).trim();
    if (answer) return answer;
    ui.warn('this one needs an answer');
  }
}

/**
 * What the host ran on before an apply: its name, and the module's
 * `host_rollout` (its cloud-init and the database URL), each null when the
 * state had none.
 */
export interface HostBeforeApply {
  host: string | null;
  rollout: string | null;
}

/**
 * Whether an apply has to reset the host. Container-Optimized OS applies
 * cloud-init at boot, and hostd reads the database URL only when it starts: a
 * host that was only restarted ran the old prepare script against the new URL,
 * found no CA where the URL names one, and lost the database. Not for a host
 * this apply made, which booted on the new ones. A host whose state predates
 * `host_rollout` has none before, and is reset once.
 */
export function hostNeedsReset(before: HostBeforeApply, after: string | null): boolean {
  return before.host !== null && after !== null && before.rollout !== after;
}

/**
 * Whether this command has to reset the host, including an apply that failed.
 *
 * Terraform can commit the new `host_rollout` and then fail on a later
 * resource. The reset ran only after an apply that exited 0, so a host whose
 * database URL had already changed kept the old prepare script, found no CA
 * where the new URL names one, and lost the database. So the exit code is not
 * asked: a plan never resets a host, and a host this apply made is
 * `hostNeedsReset`'s own answer.
 */
export function applyShouldResetHost(action: string, before: HostBeforeApply, after: string | null): boolean {
  return action === 'apply' && hostNeedsReset(before, after);
}

/** `gcloud`'s arguments for that reset. */
export function hostResetArgs(host: string, zone: string, projectId: string): string[] {
  return ['compute', 'instances', 'reset', host, '--zone', zone, '--project', projectId];
}

function list(value: string): string[] {
  return value
    .split(',')
    .map((entry) => entry.trim())
    .filter(Boolean);
}

function readBackend(): CloudBackend | null {
  if (!existsSync(backendPath())) return null;
  const parsed = JSON.parse(readFileSync(backendPath(), 'utf8')) as Partial<CloudBackend>;
  return parsed.bucket ? { bucket: parsed.bucket, prefix: parsed.prefix || 'fleetadlc' } : null;
}

function writeBackend(backend: CloudBackend): void {
  writePrivate(backendPath(), `${JSON.stringify(backend, null, 2)}\n`);
}

/**
 * `cloud configure` is often the first command on a laptop that never ran a
 * local install, so nothing had made $FLEETADLC_HOME: the settings write
 * failed with ENOENT after every question was answered and the bucket made,
 * and the answers and the new webhook secret were lost.
 */
function ensureHome(): void {
  mkdirSync(fleetHome(), { recursive: true, mode: 0o700 });
}

/** What `configure` leaves on this machine: the settings and where their bucket is. */
export function writeCloudFiles(vars: Record<string, unknown>, backend: CloudBackend): void {
  writePrivate(tfVarsPath(), `${JSON.stringify(vars, null, 2)}\n`);
  writeBackend(backend);
}

/**
 * The settings hold the webhook secret. `writeFileSync`'s mode applies only to
 * a file it creates, so one already there kept whatever mode it had.
 */
function writePrivate(path: string, text: string): void {
  ensureHome();
  writeFileSync(path, text, { mode: 0o600 });
  chmodSync(path, 0o600);
}

/**
 * What is wrong with the `terraform` on PATH, from what `terraform version
 * -json` answered; null when it is Terraform 1.6 or later. Cloud Shell's
 * /google/bin/terraform is a placeholder that prints install instructions and
 * exits 0, so a plan and an apply run through it "passed" with nothing created.
 */
export function terraformProblem(answer: GcloudResult): string | null {
  const install = 'install Terraform 1.6 or later (https://developer.hashicorp.com/terraform/install), or run infra/gcp/install.sh, which installs it';
  if (answer.code === 127) return `terraform is not installed: ${install}`;
  let version: unknown;
  try {
    version = (JSON.parse(answer.stdout) as { terraform_version?: unknown }).terraform_version;
  } catch {
    version = undefined;
  }
  if (answer.code !== 0 || typeof version !== 'string') {
    return `the terraform on this machine is not Terraform (Cloud Shell's is only a placeholder): ${install}`;
  }
  const [major = 0, minor = 0] = version.split('.').map((part) => Number.parseInt(part, 10));
  if (major < 1 || (major === 1 && minor < 6)) return `this is Terraform ${version}; ${install}`;
  return null;
}

async function terraformReady(): Promise<boolean> {
  const problem = terraformProblem(await capture('terraform', ['version', '-json']));
  if (!problem) return true;
  ui.fail(problem);
  return false;
}

async function run(command: string, args: string[], cwd?: string): Promise<number> {
  return new Promise((resolve) => {
    const child = spawn(command, args, { cwd, stdio: 'inherit' });
    child.on('close', (code) => resolve(code ?? 1));
    child.on('error', () => {
      ui.fail(`${command} is not installed`);
      ui.note(
        command === 'terraform'
          ? 'https://developer.hashicorp.com/terraform/install'
          : 'https://cloud.google.com/sdk/docs/install',
      );
      resolve(127);
    });
  });
}

/** A command's output, kept rather than shown: what `gcloud` answers to a question. */
async function capture(command: string, args: string[], cwd?: string): Promise<GcloudResult> {
  return new Promise((resolve) => {
    const child = spawn(command, args, { cwd, stdio: ['ignore', 'pipe', 'pipe'] });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (chunk: Buffer) => (stdout += chunk.toString()));
    child.stderr.on('data', (chunk: Buffer) => (stderr += chunk.toString()));
    child.on('close', (code) => resolve({ code: code ?? 1, stdout, stderr }));
    child.on('error', () => resolve({ code: 127, stdout, stderr }));
  });
}

/**
 * Runs a command with its output shown as it comes, and keeps the end of it,
 * so a Terraform failure can be said in words after Terraform has said it.
 */
async function runKeeping(command: string, args: string[], cwd?: string): Promise<{ code: number; tail: string }> {
  return new Promise((resolve) => {
    const child = spawn(command, args, { cwd, stdio: ['inherit', 'pipe', 'pipe'] });
    let tail = '';
    const keep = (chunk: Buffer, to: NodeJS.WriteStream) => {
      to.write(chunk);
      tail = (tail + chunk.toString()).slice(-64 * 1024);
    };
    child.stdout.on('data', (chunk: Buffer) => keep(chunk, process.stdout));
    child.stderr.on('data', (chunk: Buffer) => keep(chunk, process.stderr));
    child.on('close', (code) => resolve({ code: code ?? 1, tail }));
    child.on('error', () => {
      ui.fail(`${command} is not installed`);
      resolve({ code: 127, tail });
    });
  });
}

/** One of the module's outputs from the state, or null when there is none. */
async function outputValue(name: string, dir: string): Promise<string | null> {
  const read = await capture('terraform', ['output', '-raw', name], dir);
  const value = read.stdout.trim();
  return read.code === 0 && value ? value : null;
}

/**
 * Whether the project is this install's to set up in: nothing left in it by
 * an earlier install that this one's state does not hold (`cloud-leftovers.ts`).
 * False when something is, said with what to do; true otherwise, including
 * when it could not be checked.
 */
async function freshProject(settled: Record<string, unknown>, dir: string): Promise<boolean> {
  const projectId = typeof settled.project_id === 'string' ? settled.project_id : '';
  const prefix = typeof settled.name_prefix === 'string' ? settled.name_prefix : NAME_PREFIX;
  if (!projectId) return true;
  const state = await capture('terraform', ['state', 'list'], dir);
  if (state.code !== 0) {
    ui.note('could not read the Terraform state, so the project was not checked for an earlier install');
    return true;
  }
  const owned = ownedAddresses(state.stdout);
  ui.step(`checking ${projectId} for an earlier install`);
  const report = await findLeftovers({ projectId, prefix, owned }, (args) => capture('gcloud', args));
  for (const line of report.unchecked) ui.note(`not checked: ${line}`);
  if (report.found.length === 0) return true;
  const [first, ...rest] = leftoversMessage(projectId, report.found);
  ui.fail(first ?? '');
  for (const line of rest) ui.plain(line);
  return false;
}

/**
 * The bucket, made if it is not there: versioned, private, in the install's
 * own project. One that is there is used only when it is all three, or only
 * lacks versioning (`cloud-bucket.ts`). False, said with what to do, otherwise.
 */
async function ensureBucket(backend: CloudBackend, projectId: string, region: string): Promise<boolean> {
  const check = await checkBucket(backend.bucket, projectId, (args) => capture('gcloud', args));
  if (check.state === 'refused') {
    const [first, ...rest] = check.lines;
    ui.fail(first ?? '');
    for (const line of rest) ui.note(line);
    return false;
  }
  if (check.state === 'usable') {
    if (check.versioned) return true;
    ui.step(`turning on versioning for gs://${backend.bucket}`);
    return (await run('gcloud', ['storage', 'buckets', 'update', `gs://${backend.bucket}`, '--versioning'])) === 0;
  }
  ui.step(`creating gs://${backend.bucket} in ${projectId}`);
  const created = await run('gcloud', [
    'storage',
    'buckets',
    'create',
    `gs://${backend.bucket}`,
    `--project=${projectId}`,
    `--location=${region}`,
    '--uniform-bucket-level-access',
    '--public-access-prevention',
  ]);
  if (created !== 0) return false;
  // Versioned, so an apply that goes wrong can be walked back to the state before it.
  return (await run('gcloud', ['storage', 'buckets', 'update', `gs://${backend.bucket}`, '--versioning'])) === 0;
}

/**
 * The settings this install already has: this machine's copy, else the one in
 * the bucket `cloud.backend.json` names. Undefined for a new install, or when
 * neither could be read, which is said.
 */
async function existingSettings(): Promise<Record<string, unknown> | undefined> {
  const parse = (text: string, where: string): Record<string, unknown> | undefined => {
    try {
      const vars = JSON.parse(text) as unknown;
      if (vars && typeof vars === 'object' && !Array.isArray(vars)) return vars as Record<string, unknown>;
    } catch {
      // Said below.
    }
    ui.note(`${where} could not be read as settings, so this is configured as a new install`);
    return undefined;
  };
  if (existsSync(tfVarsPath())) return parse(readFileSync(tfVarsPath(), 'utf8'), tfVarsPath());
  const backend = readBackend();
  if (!backend) return undefined;
  const remote = remoteTfVars(backend);
  const copied = await capture('gcloud', ['storage', 'cat', remote]);
  if (copied.code !== 0) {
    ui.note(`could not read ${remote}, so this is configured as a new install`);
    return undefined;
  }
  return parse(copied.stdout, remote);
}

async function push(backend: CloudBackend): Promise<number> {
  const code = await run('gcloud', ['storage', 'cp', tfVarsPath(), remoteTfVars(backend)]);
  if (code === 0) ui.ok(`settings saved to ${remoteTfVars(backend)}`);
  return code;
}

/** What `afterTerraform` runs, passed in so a test can stand in for each. */
export interface AfterTerraformRunners {
  run: (command: string, args: string[]) => Promise<number>;
  outputValue: (name: string) => Promise<string | null>;
  push: () => Promise<number>;
}

/**
 * What `plan` or `apply` does once Terraform has exited with `code`: saves
 * the settings a successful apply used, resets the host when what it boots on
 * changed, and lists what is left to do by hand.
 */
export async function afterTerraform(
  action: string,
  code: number,
  before: HostBeforeApply,
  settled: Record<string, unknown>,
  runners: AfterTerraformRunners,
): Promise<void> {
  if (code === 0 && action === 'apply') {
    // What was applied is what the next operator should find.
    await runners.push();
  }

  // Outside the success branch: a failed apply can already have committed
  // the new rollout, and the host is then on the old prepare script.
  const afterRollout = action === 'apply' ? await runners.outputValue('host_rollout') : null;
  let resetMissed: string | null = null;
  if (before.host && applyShouldResetHost(action, before, afterRollout)) {
    const args = hostResetArgs(
      before.host,
      // The module's default, for settings that never named a zone.
      typeof settled.zone === 'string' && settled.zone ? settled.zone : 'us-central1-a',
      String(settled.project_id ?? ''),
    );
    ui.plain();
    ui.note(`the host's cloud-init or database settings changed: resetting ${before.host} so it boots on them`);
    if ((await runners.run('gcloud', args)) !== 0) {
      resetMissed = `gcloud ${args.join(' ')}   (the host still runs on the old settings until it is reset)`;
    }
  }

  if (code === 0 && action === 'apply') {
    const steps = postApplySteps(tfVarsPath());
    if (resetMissed) steps.unshift(resetMissed);
    ui.plain();
    ui.heading('Still to do by hand');
    for (const step of steps) ui.step(step);
  } else if (resetMissed) {
    ui.note(resetMissed);
  }
}

export async function cloud(
  config: InstallConfig,
  action: string | undefined,
  options: { provider?: string; bucket?: string; prefix?: string },
): Promise<void> {
  const provider = (options.provider ?? 'gcp') as Provider;
  if (!PROVIDERS.includes(provider)) {
    ui.fail(`no module for ${provider}`);
    ui.note(`available: ${PROVIDERS.join(', ')}`);
    process.exitCode = 1;
    return;
  }

  const dir = moduleDir(config, provider);
  if (!existsSync(dir)) {
    ui.fail(`the ${provider} module is missing from this checkout`);
    process.exitCode = 1;
    return;
  }

  switch (action) {
    case 'configure': {
      ui.heading(`Configure the ${provider} install`);
      ensureHome();
      // What the install already has is each question's default, so a run to
      // change one setting changes only that one.
      const existing = await existingSettings();
      const saved = readBackend();
      if (existing) ui.note('this install’s settings are the defaults; the webhook secret and anything not asked here are kept');
      const offered = configureDefaults(process.env);
      const projectId = await askRequired(prompt, 'project id, a new project for this install only', shown(existing, 'project_id') ?? offered.projectId);
      const region = await prompt('region', shown(existing, 'region') ?? offered.region ?? 'us-central1');
      const zone = await prompt('zone', shown(existing, 'zone') ?? `${region}-a`);
      const organization = await prompt(
        'GitHub organization (or user) this install serves',
        shown(existing, 'github_organization') ?? config.organization,
      );
      const githubClientId = await prompt('GitHub App client id', shown(existing, 'github_app_client_id') ?? config.githubClientId);
      const humans = await prompt(
        'GitHub logins that may answer gates, comma-separated',
        shown(existing, 'humans') ?? config.humans.join(','),
      );
      const consoleDomain = await askRequired(prompt, 'the console’s domain, e.g. fleetadlc.example.com', shown(existing, 'console_domain'));
      const registry = `${region}-docker.pkg.dev/${projectId}/fleetadlc`;
      const bridgeImage = await prompt('bridge image', shown(existing, 'bridge_image') ?? `${registry}/bridge:latest`);
      const consoleImage = await prompt('console image', shown(existing, 'console_image') ?? `${registry}/console:latest`);
      const hostdImage = await prompt('hostd image', shown(existing, 'hostd_image') ?? `${registry}/hostd:latest`);
      // Built by infra/local/build-bot-image.sh, which is also what a laptop
      // builds from — the pinned engine CLIs live there, in one place, so the
      // two installs cannot end up running different bots.
      const botImage = await prompt('bot image', shown(existing, 'bot_image') ?? `${registry}/bot:latest`);
      const consoleMembers = await askRequired(
        prompt,
        'who may open the console, e.g. user:alice@example.com,group:eng@example.com',
        shown(existing, 'console_members') ?? offered.consoleMembers,
      );
      const adminEmails = list(
        await prompt(
          'the console’s first admins, as emails, comma-separated',
          shown(existing, 'admin_emails') ?? consoleUsers(list(consoleMembers)).join(','),
        ),
      );
      const operators = await prompt('who may take over a terminal, a shorter list than the last', shown(existing, 'operators'));
      const typedDeployer = await prompt(
        'a GitHub repository whose workflow may deploy here, as owner/name; empty for none',
        shown(existing, 'deployer_repository'),
      );
      let deployerRepository = typedDeployer;
      let deployerRepositoryId: string | undefined;
      let deployerRepositoryOwnerId: string | undefined;
      let deployerWorkflow: string | undefined;
      if (typedDeployer) {
        const canonical = await canonicalRepository(typedDeployer);
        deployerRepository = canonical.name;
        if (!canonical.checked) {
          ui.warn(
            `GitHub did not show ${typedDeployer} without a sign-in, so it is kept as typed. Its spelling has to match GitHub's exactly, capitals included, or every deploy is refused.`,
          );
        } else if (canonical.name !== typedDeployer) {
          ui.ok(`GitHub spells it ${canonical.name}; using that`);
        }
        // Whoever can run this one workflow on the deployer branch controls
        // the install; no other workflow in the repository is admitted.
        deployerWorkflow = await prompt(
          'the workflow file that may deploy, in that repository',
          shown(existing, 'deployer_workflow') ?? DEFAULT_DEPLOYER_WORKFLOW,
        );
        deployerRepositoryId = canonical.id;
        deployerRepositoryOwnerId = canonical.ownerId;
        if (!deployerRepositoryId || !deployerRepositoryOwnerId) {
          // A private repository is a 404 without a sign-in.
          ui.note(`its ids, which the deploy is admitted by: gh api repos/${deployerRepository} --jq '.id, .owner.id'`);
          deployerRepositoryId = await prompt('the repository’s numeric id', shown(existing, 'deployer_repository_id'));
          deployerRepositoryOwnerId = await prompt('its owner’s numeric id', shown(existing, 'deployer_repository_owner_id'));
        }
      }
      // Without one, an alert opens an incident in the Cloud Monitoring
      // console and tells nobody.
      const notificationChannels = await prompt(
        'Cloud Monitoring notification channels for the alerts, as projects/<project>/notificationChannels/<id>,…; empty for none',
        shown(existing, 'notification_channels'),
      );
      const bucket = await prompt('bucket for the state and these settings', saved?.bucket ?? `${projectId}-fleetadlc-tfstate`);

      // An install pulled from before the rename keeps its state under `fleet`.
      const backend = { bucket, prefix: saved?.prefix ?? 'fleetadlc' };
      if (!(await ensureBucket(backend, projectId, region))) {
        ui.fail(`gs://${bucket} was not used; nothing was uploaded`);
        process.exitCode = 1;
        return;
      }

      const vars = configuredVars(
        existing,
        {
          provider,
          projectId,
          region,
          zone,
          organization,
          githubClientId,
          humans: list(humans),
          consoleDomain,
          bridgeImage,
          consoleImage,
          hostdImage,
          botImage,
          consoleMembers: list(consoleMembers),
          adminEmails,
          operators: list(operators),
          deployerRepository,
          deployerRepositoryId,
          deployerRepositoryOwnerId,
          deployerWorkflow,
          notificationChannels: list(notificationChannels),
        },
        config.ports.hostd,
        () => randomBytes(32).toString('hex'),
      );
      writeCloudFiles(vars, backend);
      ui.ok(`wrote ${tfVarsPath()}`);
      const warning = noAdminWarning(adminEmails, tfVarsPath());
      if (warning) ui.warn(warning);
      process.exitCode = await push(backend);
      ui.step('next: fleetadlc cloud plan');
      return;
    }

    case 'pull': {
      const bucket = options.bucket ?? readBackend()?.bucket;
      if (!bucket) {
        ui.fail('which bucket? fleetadlc cloud pull --bucket <name>');
        process.exitCode = 1;
        return;
      }
      const backend = { bucket, prefix: options.prefix ?? 'fleetadlc' };
      // Checked against the project the settings name before anything here is
      // replaced: a bucket someone else made could hand this machine settings
      // that add them as an operator.
      const pulled = await pullSettings({ bucket, remote: remoteTfVars(backend) }, (args) => capture('gcloud', args));
      if (!pulled.ok) {
        const [first, ...rest] = pulled.lines;
        ui.fail(first ?? '');
        for (const line of rest) ui.note(line);
        ui.note(`${tfVarsPath()} was left as it was`);
        process.exitCode = 1;
        return;
      }
      writePrivate(tfVarsPath(), pulled.text);
      writeBackend(backend);
      ui.ok(`this machine now runs the install whose state is in gs://${bucket}/${backend.prefix}`);
      if (!pulled.versioned) {
        ui.warn(`gs://${bucket} is not versioned, so a bad apply cannot be walked back`);
        ui.note(`gcloud storage buckets update gs://${bucket} --versioning`);
      }
      process.exitCode = 0;
      return;
    }

    case 'push': {
      const backend = readBackend();
      if (!backend || !existsSync(tfVarsPath())) {
        ui.fail('this machine has no cloud configuration to save');
        ui.note('fleetadlc cloud configure, or fleetadlc cloud pull --bucket <name>');
        process.exitCode = 1;
        return;
      }
      process.exitCode = await push(backend);
      return;
    }

    case 'plan':
    case 'apply':
    case 'output': {
      const backend = readBackend();
      if (!backend || !existsSync(tfVarsPath())) {
        ui.fail('this machine has no cloud configuration');
        ui.note('fleetadlc cloud configure, or fleetadlc cloud pull --bucket <name> for an install that exists');
        process.exitCode = 1;
        return;
      }

      const { vars: settled, pinned } = pinNamePrefix(JSON.parse(readFileSync(tfVarsPath(), 'utf8')) as Record<string, unknown>);
      if (pinned) {
        writePrivate(tfVarsPath(), `${JSON.stringify(settled, null, 2)}\n`);
        ui.note(`these settings predate FleetADLC: pinned name_prefix = "${LEGACY_NAME_PREFIX}" so the resources keep their names`);
        await push(backend);
      }

      ui.heading(`terraform ${action} (${provider}, state in gs://${backend.bucket}/${backend.prefix})`);
      if (!(await terraformReady())) {
        process.exitCode = 1;
        return;
      }
      const init = await run('terraform', ['init', '-input=false', ...backendArgs(backend)], dir);
      if (init !== 0) {
        process.exitCode = init;
        return;
      }

      if (action === 'output') {
        process.exitCode = await run('terraform', ['output'], dir);
        return;
      }

      // Before Terraform changes anything: a project an earlier install was
      // torn down from fails halfway through an apply, on names Google keeps.
      if (!(await freshProject(settled, dir))) {
        process.exitCode = 1;
        return;
      }

      const before: HostBeforeApply =
        action === 'apply'
          ? { host: await outputValue('host_name', dir), rollout: await outputValue('host_rollout', dir) }
          : { host: null, rollout: null };

      const { code, tail } = await runKeeping(
        'terraform',
        action === 'apply'
          ? ['apply', `-var-file=${tfVarsPath()}`, '-input=false']
          : ['plan', `-var-file=${tfVarsPath()}`, '-input=false'],
        dir,
      );
      const explained = code === 0 ? null : explainTerraformFailure(tail);
      if (explained) {
        ui.plain();
        ui.fail(explained);
      }

      await afterTerraform(action, code, before, settled, {
        run,
        outputValue: (name) => outputValue(name, dir),
        push: () => push(backend),
      });
      process.exitCode = code;
      return;
    }

    case 'validate': {
      if (!(await terraformReady())) {
        process.exitCode = 1;
        return;
      }
      const init = await run('terraform', ['init', '-backend=false', '-input=false'], dir);
      if (init !== 0) {
        process.exitCode = init;
        return;
      }
      process.exitCode = await run('terraform', ['validate'], dir);
      return;
    }

    default:
      ui.fail(`unknown cloud command: ${action ?? '(none)'}`);
      ui.note('try: fleetadlc cloud configure | pull | push | plan | apply | output | validate');
      process.exitCode = 1;
  }
}
