import { getSecretStore, internalSecretRef, type SecretStore } from '@fleetadlc/github';

export interface TaskToken {
  token: string;
  expiresAt: string | null;
  login: string;
  /**
   * Whether GitHub narrowed it to the task's repository. False when the
   * install has no app client secret, or GitHub would not: the account's own
   * token, which reaches every repository the account can.
   */
  scoped?: boolean;
}

/**
 * hostd holds no refresh token. GitHub rotates a refresh token on every use, so
 * two components refreshing the same credential invalidate each other and the
 * bot's account can only be recovered by a person repeating the device flow —
 * which is why the bridge is the install's only broker and hostd asks it for a
 * token when a task starts.
 *
 * The secret that admits it is generated by the bridge on first start, so hostd
 * may come up before it exists and re-reads it once on a refusal rather than
 * caching a miss for the life of the process.
 */
export class TokenClient {
  private secret: string | null = null;

  constructor(
    private readonly bridgeUrl: string,
    private readonly store: SecretStore = getSecretStore(),
  ) {}

  private async sharedSecret(reread = false): Promise<string | null> {
    if (this.secret && !reread) return this.secret;
    this.secret = await this.store.get(internalSecretRef());
    return this.secret;
  }

  private async request(bot: string, secret: string, repository: string | null): Promise<Response> {
    return fetch(`${this.bridgeUrl}/internal/tokens/${encodeURIComponent(bot)}`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'x-fleetadlc-internal-secret': secret },
      body: JSON.stringify({ purpose: 'task', ...(repository ? { repository } : {}) }),
    });
  }

  /**
   * The token a task runs with. Any failure throws with the bridge's reason,
   * or the network's: a task started without its token cloned a private
   * repository into git's "could not read Username", or ran a whole session
   * on a public one and failed at its first comment, with the reason only in
   * hostd's log. A bot with no GitHub login is never asked about.
   *
   * `repository` (`owner/name`) is the task's: the bridge narrows the token to
   * it, since every crew account is in every repository OpenADLC manages, and
   * refuses one it does not manage. A task in no repository gets the
   * account's token, as before.
   */
  async tokenForTask(bot: string, repository: string | null = null): Promise<TaskToken> {
    let secret = await this.sharedSecret();
    if (!secret) {
      throw new Error(`${bot} has no GitHub token: the bridge has not written hostd's internal secret yet. Start the bridge, then try again.`);
    }

    let response: Response;
    try {
      response = await this.request(bot, secret, repository);

      // The bridge writes the secret on its first start, which may come after
      // hostd found none, so one refusal is worth a second look before it
      // counts as a failure.
      if (response.status === 401) {
        secret = (await this.sharedSecret(true)) ?? secret;
        response = await this.request(bot, secret, repository);
      }
    } catch (error) {
      throw new Error(`${bot} has no GitHub token: the bridge's token service is unreachable (${error instanceof Error ? error.message : error})`);
    }

    if (!response.ok) {
      const detail = (await response.text().catch(() => '')).trim();
      let reason = detail;
      try {
        const parsed = JSON.parse(detail) as { error?: unknown };
        if (typeof parsed.error === 'string') reason = parsed.error;
      } catch {
        // Not JSON: the text as it came.
      }
      throw new Error(`${bot} has no GitHub token: the bridge would not mint one (${response.status}) ${reason.slice(0, 300)}`.trim());
    }

    const token = (await response.json()) as TaskToken;
    if (repository && token.scoped === false) {
      console.warn(
        `[hostd] ${bot}'s GitHub token for ${repository} is not scoped to the repository: it reaches every repository the account can. ` +
          'Give the install the app’s client secret in Settings → GitHub.',
      );
    }
    return token;
  }
}
